cluster.name: elasticsearch
network.host: 0.0.0.0
transport.tcp.port: 9300
xpack.security.enabled: false
path.logs: /usr/share/elasticsearch/logs
path.data: usr/share/elasticsearch/logs
path.repo: ["/usr/share/elasticsearch/backup"]


